### ISSUE TITLE
Just help executing the program.

### ISSUE THREAD

**Issue by Panjrsx** [poirierjm/fortniteDiscordBot#2]
Changed everything accordingly inside bot.py
After that I used 'Git for Windows' to execute the command and find: "Bash: Python3: Command Not Found" 

Also, how can I import the discord api? ErrorModuleNotFound: discord

**Comment by poirierjm** [comment]
Your first error mean python 3 is not installed on your git for windows.

For your second question, go to https://discordapp.com/developers/applications/me/ 
Then create an app and search for "Token" and click on reveal. That the token you need for the bot.py script.

**Comment by poirierjm** [comment]
To add the bot to your discord, from the app created copy your Client ID into this URL: https://discordapp.com/oauth2/authorize?&client_id=CLIENT_ID_HERE&scope=bot&permissions=470019135 and paste this URL into a web navigator.
