### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Intrinsic7** [poirierjm/fortniteDiscordBot#4]
https://gyazo.com/bd60b6cac5c2ff548cd4fe27ce78a3e3
I tried setting up the bot but I can even get the script.sh to run or even the bot.py
nothing is working for me

**Comment by poirierjm** [comment]
Go in the windows store and search for Ubuntu, get this instead of git for windows

**Comment by Intrinsic7** [comment]
I can't execute the file with Ubuntu, won't allow me to do so.

all I keep getting is "/c/Users/brayd/OneDrive/Desktop/FortniteTracker/script.sh: line 2: python3: command not found"
- I know that's from not having it installed but how do I install python to ubuntu or git bash...

**Comment by DemonBray** [comment]
all I keep getting is "/c/Users/brayd/OneDrive/Desktop/FortniteTracker/script.sh: line 2: python3: command not found"

**Comment by Intrinsic7** [comment]
Any way I can get some help another way?

**Comment by poirierjm** [comment]
My discord: Wiz#8991

You need to install python on your bash
